In [7]:
import numpy as np
from sklearn.metrics import confusion_matrix
# from sklearn.metrics import multilabel_confusion_matrix

y_true = np.array([[1,0,0, 0], [1,0,0, 0], [1,0,0, 0], [0,1,1,0], [0,1,1,0], [0,1,1,0], [0,1,1,0]])
y_pred = np.array([[1,0,0, 0], [0,1,0, 0], [0,1,1, 0], [1,0,1,0], [1,0,0,1], [0,1,0,1], [0,1,1,0]])

labels = ["B", "T", "D", "C"]

conf_mat_dict={}

for label_col in range(len(labels)):
    y_true_label = y_true[:, label_col]
    y_pred_label = y_pred[:, label_col]
    conf_mat_dict[labels[label_col]] = confusion_matrix(y_pred=y_pred_label, y_true=y_true_label)


for label, matrix in conf_mat_dict.items():
    print("Confusion matrix for label {}:".format(label))
    print(matrix)

Confusion matrix for label B:
[[2 2]
 [2 1]]
Confusion matrix for label T:
[[1 2]
 [2 2]]
Confusion matrix for label D:
[[2 1]
 [2 2]]
Confusion matrix for label C:
[[5 2]
 [0 0]]
